version: '3.9'

services:
  metabase:
    build:
      context: .
      dockerfile: Dockerfile.custom
    container_name: metabase
    hostname: metabase
    restart: always
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabaseappdb
      MB_DB_PORT: 5432
      MB_DB_USER: metabase_user
      MB_DB_PASS: metabase_password_extra_secure
      MB_DB_HOST: metabase-db
    networks:
      - metabase-network
    depends_on:
      - metabase-db
      - ai-middleware

  ai-middleware:
    build:
      context: ./automation/ai
      dockerfile: Dockerfile # Creado a continuacion
    container_name: metabase-ai-middleware
    restart: always
    environment:
      # Las llaves deben ser inyectadas como variables de entorno directamente en la caja de Environment de Portainer.
      # GEMINI_API_KEY: "tu-llave"
      # GROK_API_KEY: "tu-llave"
      POSTGRES_DW_HOST: metabase-db
      POSTGRES_DW_NAME: metabaseappdb
      POSTGRES_DW_USER_ADMIN: metabase_user
      POSTGRES_DW_PASSWORD: metabase_password_extra_secure
    networks:
      - metabase-network

  metabase-db:
    image: postgres:15-alpine
    container_name: metabase-db
    hostname: metabase-db
    restart: always
    environment:
      POSTGRES_USER: metabase_user
      POSTGRES_PASSWORD: metabase_password_extra_secure
      POSTGRES_DB: metabaseappdb
    volumes:
      - metabase-db-data:/var/lib/postgresql/data
    networks:
      - metabase-network

networks:
  metabase-network:
    driver: bridge

volumes:
  metabase-db-data:
