FROM node:22-bullseye AS builder

WORKDIR /home/node

RUN apt-get update && apt-get install -y wget apt-transport-https gpg curl git python3 python3-pip python-is-python3 build-essential \
    && wget -qO - https://packages.adoptium.net/artifactory/api/gpg/key/public | gpg --dearmor | tee /etc/apt/trusted.gpg.d/adoptium.gpg > /dev/null \
    && echo "deb https://packages.adoptium.net/artifactory/deb $(awk -F= '/^VERSION_CODENAME/{print$2}' /etc/os-release) main" | tee /etc/apt/sources.list.d/adoptium.list \
    && apt-get update && apt install temurin-21-jdk -y \
    && curl -O https://download.clojure.org/install/linux-install-1.12.0.1488.sh \
    && chmod +x linux-install-1.12.0.1488.sh && ./linux-install-1.12.0.1488.sh

# Install UV using python pip for global, reliable PATH access
RUN pip3 install uv

COPY . .
RUN git config --global --add safe.directory /home/node
RUN npm install -g bun
RUN bun install --frozen-lockfile

# Modificación de Branding y Compilación Final
RUN INTERACTIVE=false CI=true MB_EDITION=oss bin/build.sh > clojure_build.log 2>&1 || (tail -n 250 clojure_build.log && exit 1)

# ---- RUNNER ----
FROM eclipse-temurin:21-jre-alpine AS runner

ENV FC_LANG=en-US LC_CTYPE=en_US.UTF-8

RUN apk add -U bash fontconfig curl font-noto font-noto-arabic font-noto-hebrew font-noto-cjk java-cacerts && \
    apk upgrade && rm -rf /var/cache/apk/* && mkdir -p /app/certs /plugins && chmod a+rwx /plugins

COPY --from=builder /home/node/target/uberjar/metabase.jar /app/
COPY bin/docker/run_metabase.sh /app/

EXPOSE 3000
ENTRYPOINT ["/app/run_metabase.sh"]
