FROM python:3.11-slim

WORKDIR /app

# Instalar dependencias del sistema para PostgreSQL / Compilacion
RUN apt-get update && apt-get install -y libpq-dev gcc && rm -rf /var/lib/apt/lists/*

# Copiar dependencias de Python e instalar
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar fuente de la app FastAPI
COPY api/ /app/

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
