version: '3.9'

services:
  metabase:
    ports:
      - "3000:3000"
    environment:
      MB_SITE_URL: http://localhost:3000
    volumes:
      - ../src/lw:/app/src/lw
      - ../frontend/src/lw:/app/frontend/src/lw

  nginx:
    profiles:
      - dont-start-in-dev
